feat:polaris registry and resolver implementation to Kitex
kitex-contrib/registry-polaris pull request #1
Opened 2021-12-27 14:23 UTC by liu-song

2021-12-29 08:55 UTC, GuangmingLuo commented
@liu-song 请修复下两个失败的检查吧

2021-12-29 09:01 UTC, liu-song commented
好的，这个我后面一起修复一下

2021-12-30 07:17 UTC, GuangmingLuo commented on README.md
> +    client, err := echo.NewClient("echo", client.WithResolver(r))
You may add this as well:
https://www.cloudwego.io/docs/kitex/tutorials/framework-exten/service_discovery/#usage-example

2021-12-30 07:27 UTC, GuangmingLuo commented on resolver.go
> +			klog.Infof("instance getOneInstance is %s:%d", instance.GetHost(), instance.GetPort())
这个地方打 info 日志会影响性能吧，改成 debug ？

2022-01-03 14:52 UTC, liu-song commented on README.md
> +    client, err := echo.NewClient("echo", client.WithResolver(r))
ok,已经添加了

2022-01-03 14:54 UTC, liu-song commented on resolver.go
> +			klog.Infof("instance getOneInstance is %s:%d", instance.GetHost(), instance.GetPort())
换成zap的了；)

2022-01-04 06:11 UTC, GuangmingLuo requested changes

2022-01-04 06:11 UTC, GuangmingLuo commented on common.go
> +type instanceInfo struct {
type instanceInfo is unused

2022-01-04 06:11 UTC, GuangmingLuo commented on common.go
> +	addr := PolarisInstance.GetHost() + ":" + strconv.Itoa(int(PolarisInstance.GetPort()))
PolarisInstance.GetPort() 可能为空么？

2022-01-04 06:11 UTC, GuangmingLuo commented on example/client/main.go
> +	r, err := polaris.NewPolarisResolver([]string{"127.0.0.1:8091"})
ip:port 不能从配置文件 polaris.yaml 里面读取吗？

2022-01-04 06:11 UTC, GuangmingLuo commented on registry.go
> +	ticker := time.NewTicker(5 * time.Second)
心跳时间能否设置从配置文件中读取，如果没有配置，则读取默认值（定义常量）

2022-01-04 06:12 UTC, GuangmingLuo commented
more reviewdog issues to be solved. @liu-song

2022-01-04 06:29 UTC, GuangmingLuo commented on registry.go
> +func (pr *polarisRegistry) IsAvailable() bool {
Receiver names are different， svc or pr ?

2022-01-04 06:58 UTC, liu-song commented on common.go
> +type instanceInfo struct {
ok,我后面删掉

2022-01-04 06:59 UTC, liu-song commented on common.go
> +	addr := PolarisInstance.GetHost() + ":" + strconv.Itoa(int(PolarisInstance.GetPort()))
Polaris的Instance由四元组构成，（服务名+命名空间+host+port）构成，这个getport 不会为空

2022-01-04 07:01 UTC, liu-song commented on example/client/main.go
> +	r, err := polaris.NewPolarisResolver([]string{"127.0.0.1:8091"})
我改下吧

2022-01-04 07:02 UTC, liu-song commented on registry.go
> +	ticker := time.NewTicker(5 * time.Second)
OK，我改成常量吧

2022-01-04 07:03 UTC, liu-song commented on registry.go
> +func (pr *polarisRegistry) IsAvailable() bool {
:sweat_smile: svc

2022-01-04 07:06 UTC, liu-song commented
@GuangmingLuo 还有其他人的review吗，review之后，我一起改下吧，thx

2022-01-04 08:10 UTC, liu-song commented
hi, @chuntaojun ,please take a review ,thanks.

2022-01-04 08:56 UTC, YangruiEmma commented
> @GuangmingLuo 还有其他人的review吗，review之后，我一起改下吧，thx

等我这周抽空和consul的一起review下，其他的可以先改哈

2022-01-05 03:15 UTC, GuangmingLuo commented on common.go
> +func LoadpolarisAddress(confpath string) ([]string, error) {
驼峰：LoadPolarisAddress

2022-01-05 03:17 UTC, GuangmingLuo commented on common.go
> +	if confpath != "" && model.IsFile(confpath) {
polarisaddresses -> polarisAddresses

2022-01-05 03:32 UTC, GuangmingLuo commented
common.go 这个文件，有空可以写点单测

2022-01-05 05:32 UTC, liu-song commented
> common.go 这个文件，有空可以写点单测

我后面加下

2022-01-05 06:20 UTC, GuangmingLuo commented on common.go
> +func ChangePolarisInstanceToKitx(PolarisInstance model.Instance) discovery.Instance {
漏了一个typo， Kitx -> Kitex

2022-01-05 06:20 UTC, GuangmingLuo commented on common.go
> +func LoadPolarisAddress(confpath string) ([]string, error) {
最好利用goland插件检查下，是否还有类似的编码规范问题哈。confpath -> confPath

2022-01-06 06:16 UTC, GuangmingLuo commented on example/server/main.go
> +		ServiceName: "golang",
ServiceName: better to use kitex-server or echo-server

2022-01-06 07:05 UTC, liu-song commented on example/server/main.go
> +		ServiceName: "golang",
OK。为了避免混淆，直接换成echo 了

2022-01-06 07:48 UTC, chuntaojun commented on polaris.yaml
> +global:
在正式源码中，这个文件应该不需要存在才对，可以在readme中指向polaris-go的polaris.yaml，有完整的配置文件信息解释

2022-01-06 07:48 UTC, chuntaojun commented on registry.go
> +	protocolForKitex            = "tcp"
是不是改为Kitex好一点？

2022-01-06 07:48 UTC, chuntaojun commented on registry.go
> +	go svr.doHeartbeat(param)
实例反注册的话，心跳也应该一并取消，使用context.WithCacnel，反注册的时候执行一下cancel

2022-01-06 07:48 UTC, chuntaojun commented on registry.go
> +		case <-svr.ctx.Done():
这里不应该已svr.ctx为准，而是每一个实例有自己的心跳上报生命周期

2022-01-06 07:48 UTC, chuntaojun commented on registry.go
> +	ctx        context.Context
ctx 是不是不合适作为 struct 中的成员

2022-01-06 07:48 UTC, chuntaojun commented on registry.go
> +			Namespace: polarisDefaultNamespace,
用户不能自己指定命名空间吗？

2022-01-06 07:48 UTC, chuntaojun commented on resolver.go
> +		namespace:  polarisDefaultNamespace,
同理，命名空间应当是可以用户可配置的，没有的话才走默认的命名空间

2022-01-06 08:14 UTC, liu-song commented on registry.go
> +	protocolForKitex            = "tcp"
就我目前了解到的是要用tcp，不然连接好像建立不上

2022-01-06 08:19 UTC, liu-song commented on registry.go
> +			Namespace: polarisDefaultNamespace,
目前只支持默认的命名空间了，kitex 里面的registry.info 目前还没对namespace具体定义 ，携带namespace需要通过Info.Tags 携带，先简单实现默认的命名空间吧

2022-01-06 08:24 UTC, liu-song commented on registry.go
> +	go svr.doHeartbeat(param)
ok

2022-01-06 08:30 UTC, liu-song commented on polaris.yaml
> +global:
OK，我后面删一下

2022-01-06 09:27 UTC, chuntaojun commented on registry.go
> +	protocolForKitex            = "tcp"
这个不是只是在北极星标注下实例的协议吗？应该和链接没关系吧？难道有使用到这个字段？

2022-01-06 10:00 UTC, liu-song commented on registry.go
> +	protocolForKitex            = "tcp"
之前写的时候尝试改过，example 中的client 端是用到了这个

2022-01-06 10:51 UTC, chuntaojun commented on registry.go
> +			Namespace: polarisDefaultNamespace,
我觉得还是要支持下，因为别的组件都支持配置命名空间，这应该是最基本的配置能力我觉得

2022-01-06 10:55 UTC, liu-song commented on registry.go
> +			Namespace: polarisDefaultNamespace,
好的，我加下

2022-01-11 01:56 UTC, liu-song commented on registry.go
> +	protocolForKitex            = "tcp"
删除了这个protocolForKitex ，改成注册实例的时候网络协议，client端会用到

2022-01-11 01:58 UTC, liu-song commented on registry.go
> +			Namespace: polarisDefaultNamespace,
client 通过 client.WithTag 携带 namespace ,server端通过WithRegistryInfo中info.Tags 携带namespace

2022-01-11 03:52 UTC, GuangmingLuo requested changes

2022-01-11 03:52 UTC, GuangmingLuo commented on example/server/main.go
> +	Conf, err := config.LoadConfigurationByFile(confPath)
“fail to read context file polaris.yaml, cause: open polaris.yaml: no such file or directory”
confPath not working in mac ?
same for client/main.go

2022-01-11 03:52 UTC, GuangmingLuo commented on common.go
> +func SplitDescription(description string) (string, string) {
Lack of comments  for exported func, same for bellow funcs.

2022-01-11 06:58 UTC, GuangmingLuo commented on example/server/main.go
> +	Conf, err := config.LoadConfigurationByFile(confPath)
find a related bug: https://github.com/polarismesh/polaris-go/issues/31

2022-01-11 07:24 UTC, chuntaojun commented on example/client/main.go
> +	namespace := Conf.Consumer.ServicesSpecific[0].Namespace
这个不是这么用的，把这个使用方式去掉

2022-01-11 07:24 UTC, chuntaojun commented on example/client/polaris.yaml
> +  servicesSpecific:
同理，这个配置去掉，这个不是用于获取provider设置namespace的

2022-01-11 07:34 UTC, liu-song commented on example/client/main.go
> +	namespace := Conf.Consumer.ServicesSpecific[0].Namespace
意思是不在配置文件中配置实例的namespace?

2022-01-12 01:00 UTC, liu-song commented on example/server/main.go
> +	Conf, err := config.LoadConfigurationByFile(confPath)
goland 运行配置里面配置对应的working directory 即可，命令行无问题

2022-01-12 01:03 UTC, liu-song commented on example/client/main.go
> +	namespace := Conf.Consumer.ServicesSpecific[0].Namespace
done

2022-01-12 03:28 UTC, chuntaojun approved these changes

2022-01-12 06:00 UTC, GuangmingLuo approved these changes

2022-01-12 06:04 UTC, merged

2022-01-12 06:14 UTC, chuntaojun commented
nice